### ISSUE TITLE
Cannot rebuild Formsindex: This index cannot be rebuilt because it has no assigned IIndexPopulator 

### ISSUE THREAD

**Issue by mcl-sz** [Novicell/Novicell.Examine.ElasticSearch#15]
Hi,

I would like to use the ElastichSearch also for the Form indexes.
I have added `<add key="examine:ElasticSearch[FormsConfig].Url" value="http://localhost:9200" />` to Web.config, but when I try to reindex the button is disabled and the message " This index cannot be rebuilt because it has no assigned IIndexPopulator" is shown.

![afbeelding](https://user-images.githubusercontent.com/18614643/103489117-6bce6b80-4e12-11eb-87c9-c63d0075b392.png)

Do i miss some some configuration?

**Comment by bielu** [comment]
@mcl-sz can you tell me version of Novicell.Examine.ElasticSearch.Umbraco.Forms and Forms and Umbraco?

**Comment by bielu** [comment]
@mcl-sz I just pushed newer version, I find Umbraco form base populator is write in way that is looking for name and comparision is case sensitive and I had to reimplement that populator...

**Comment by inetzo** [comment]
Hi @bielu , i have the same message by diffrent configurations. I would like to use it with Umbraco 8.6.4 with Forms 8.4.1 (added your package via source) but i get the same message using Umbraco 8.10 with Forms 8.6.0. I installed all Novicell ElasticSearch packages of version 1.0.0-Beta.2940

**Comment by bielu** [comment]
@inetzo version 1.0.0-Beta.2945 should resolve that issue as mentioned above, umbraco is handling really bad way index populator in forms and pdf index
commit to fix forms:
https://github.com/Novicell/Novicell.Examine.ElasticSearch/commit/1a5cff2f5b3e26251afaceb60336eab2930c97b9
commit to fix pdf editor (that will be next build version):
https://github.com/Novicell/Novicell.Examine.ElasticSearch/commit/bc512e78175e82bde833a48ba08b9c76b2d101c2

**Comment by mcl-sz** [comment]
Hi @bielu , many thanks for your quick response. I've updated to 1.0.0-Beta.2946 but unfortunatly the same message is still showing up. I'm using Umbraco 8.10 with Forms 8.6.

**Comment by bielu** [comment]
@mcl-sz my bad, forgot to register new populator correctly in umbraco, next available version should resolve that issue (that will be published in few minutes)

**Comment by mcl-sz** [comment]
Works like a charm, thank you very much @bielu !

**Comment by bielu** [comment]
then I am closing ticket, and happy to help in future :)

**Comment by gurumurthyjv** [comment]
Hi @bielu ,

I am also, facing the same issue now, not able to rebuild External and Internal indexes, i am using ExamineX with azure search. if i disable ExamineX then every thing works normal from local index, but facing issues with azure indexes.

Using Umbraco v8.14.0 and ExamineX v2.0.0

Any inputs/support on this, would be helpful.

![image](https://user-images.githubusercontent.com/36879551/136200588-55dc312f-fbd1-4ea8-bebe-f992a2d57e78.png)

Thanks,
Gurumurthy J V

**Comment by bielu** [comment]
@gurumurthyjv you can't use examinex and elasticsearch provider in same time.

**Comment by gurumurthyjv** [comment]
@bielu ,

I am not using elasticsearch, using only ExamineX

**Comment by bielu** [comment]
@gurumurthyjv then please report issue on examinex, not elasticsearch provider :)
